# Generated by Django 3.1.6 on 2021-02-23 18:14

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_auto_20210219_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
